pre-release-commit-message = "Release {{version}}"
tag-message = "Release {{version}}"
tag-name = "{{version}}"
sign-commit = true
sign-tag = true

pre-release-replacements = [
  {file="README.md", search="android-sdkmanager-rs = .*", replace="{{crate_name}} = \"{{version}}\""},
  {file="README.tpl", search="android-sdkmanager-rs = .*", replace="{{crate_name}} = \"{{version}}\""},
]
